const USER_LOGIN = "USER_LOGIN";
const USER_LOGOUT = "USER_LOGOUT";
const USER_UPDATE = "USER_UPDATE"
const GET_CITIES = "GET_CITIES";
const GET_CAREERS = "GET_CAREERS"
const GET_SALARIES = "GET_SALARIES";
const GET_POSITIONS = "GET_POSITIONS";
const GET_EXPERIENCES = "GET_EXPERIENCES";
const GET_WORKING_FORMS = "GET_WORKING_FORMS";
const OPEN_ALERT = "OPEN_ALERT"
const CLOSE_ALERT = "CLOSE_ALERT"
const OPEN_ALERT_DIALOG = "OPEN_ALERT_DIALOG"
const CLOSE_ALERT_DIALOG = "CLOSE_ALERT_DIALOG"

export {
  USER_LOGIN,
  USER_LOGOUT,
  USER_UPDATE,
  GET_CITIES,
  GET_CAREERS,
  GET_SALARIES,
  GET_POSITIONS,
  GET_EXPERIENCES,
  GET_WORKING_FORMS,
  OPEN_ALERT,
  CLOSE_ALERT,
  OPEN_ALERT_DIALOG,
  CLOSE_ALERT_DIALOG
};
